# demo
configuration: Release

before_build:
  - nuget restore

build:
  verbosity: minimal
  publish_wap: true
  
deploy:
  - provider: Environment
    name: LS

services:
  - mssql2016
  
before_package:
  - cmd: dir
